name: Fetch and Update Haberler

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Fetch haberler data
        run: |
          mkdir -p data
          curl -s https://services.karabuk.bel.tr/jsons-karabukbeltr/data/data-haberler.json > data/haberler.json
          
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update haberler data"
          file_pattern: data/haberler.json
