name: Fetch and Update Haberler

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Fetch haberler data
        run: |
          mkdir -p data
          curl -s https://services.karabuk.bel.tr/jsons-karabukbeltr/data/data-haberler.json > data/haberler.json
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/haberler.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update haberler data $(date)" && git push)
